import React, { useEffect } from 'react';

const products = [
  { number:'01', key:'runner', status:'Available', name:'Runner Lock', description:'Move first. Scroll later. Runner Lock helps you follow through on a workout or destination before distracting apps return.', href:'https://apps.apple.com/us/app/runner-lock-block-apps/id6802343455', link:'View on the App Store', visual:<img className="runner-shot" src="/assets/runner-lock-app-store.jpg" alt="Runner Lock App Store product preview" /> },
  { number:'02', key:'reader', status:'Coming soon', name:'Reader Lock', description:'A reading version of the lock. Read, leave one thought, and build a visible 90-day reading journey instead of opening another feed.', meta:'iPhone · Reading & reflection', visual:<div className="reading-grid" aria-label="29 of 90 reading days completed">{Array.from({length:90},(_,i)=><span key={i}/>)}</div> },
  { number:'03', key:'siteproof', status:'Available', name:'SiteProof Camera', description:'Document field work with context built in. Add time, address, coordinates, altitude, and direction directly to photos and videos.', href:'https://apps.apple.com/app/id6781711880', link:'View on the App Store', visual:<div className="device"><img src="/assets/siteproof.png" alt="SiteProof Camera app preview" /></div> },
  { number:'04', key:'flipy', status:'Available', name:'Flipy Clock', description:'A native macOS flip clock for countdowns, focused sessions, and the dates you want to keep in view.', href:'https://apps.apple.com/app/id6775473521', link:'View on the Mac App Store', visual:<div className="clock" aria-label="Flip clock showing 08 26"><div className="digit">08</div><div className="digit">26</div></div> },
];

export default function App(){
  useEffect(()=>{const observer=new IntersectionObserver(items=>items.forEach(item=>{if(item.isIntersecting){item.target.classList.add('visible');observer.unobserve(item.target)}}),{threshold:.1});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));return()=>observer.disconnect()},[]);
  return <>
    <header className="wrap"><a className="wordmark" href="#top">BUAM SPACE</a><nav className="nav" aria-label="Primary"><a href="#products">Products</a><a href="#direction">Direction</a><a href="#about">About</a><a href="mailto:yui.ai.support@buamspace.site">Contact</a></nav></header>
    <main id="top">
      <section className="intro wrap"><h1>Independent apps for attention, work, and everyday life.</h1><div className="intro-copy"><p>Buam Space is a small software studio in Seoul. We make focused tools that help people spend their time with more intention.</p><a className="text-link" href="#products">View selected products</a></div></section>
      <section id="products" className="wrap"><div className="index-head"><span>No.</span><span>Selected products</span><span>Status</span></div>{products.map(product=><article className={`product ${product.key} reveal`} key={product.key}><div className="number">{product.number}</div><div className="product-copy"><div className="status">{product.status}</div><h2>{product.name}</h2><p>{product.description}</p>{product.href?<a className="text-link" href={product.href} target="_blank" rel="noreferrer">{product.link}</a>:<span className="meta">{product.meta}</span>}</div><div className="visual">{product.visual}</div></article>)}</section>
      <section id="direction" className="direction wrap reveal"><div className="section-tag">Direction</div><h2>One system for a more balanced day.</h2><div className="direction-copy"><p>Runner Lock will grow beyond a simple blocker, while Reader Lock brings the same idea to reading. Over time, they will connect into an AI lifestyle companion that helps people balance movement, reading, focus, and rest.</p><p>We are starting with clear, useful products and expanding only where intelligence can make daily choices genuinely easier.</p></div></section>
      <section id="about" className="about"><div className="about-inner wrap"><div className="about-top"><div className="section-tag">About</div><h2>Small team.<br/>Useful software.</h2><div className="about-copy"><p>Buam Space is an independent studio based in Seoul. We build products around specific everyday problems, with calm interfaces and a clear reason to exist.</p><a className="contact" href="mailto:yui.ai.support@buamspace.site">yui.ai.support@buamspace.site</a></div></div><div className="footer"><span>© {new Date().getFullYear()} Buam Space</span><span>Seoul, South Korea</span></div></div></section>
    </main>
  </>
}
